-- extends 'project.yaml'

[config_metadata]
    == super()
    -- set ns.config_name = "Baseline"
    -- set ns.config_description = "Baseline configuration using Tiny Experiments defaults"
    -- set ns.model_name = "control"
    -- set ns.log_name = "control"