-- extends 'project.yaml'

## Packed format packs multiple examples into each 4096 token sequence
## This increases the effective batch size, thus we rescale various 
## parameters to approximate the baseline "1300" sequence length config.
[config_metadata]
    == super()
    -- set ns.config_name = "7B 1 GPU"
    -- set ns.config_description = "Train a 7B model on 1 GPU (24 GB)"
    -- set ns.log_name = "7b_1gpu"
    -- set ns.default_max_steps = 500
    -- set ns.max_eval_steps = 10

[trainer_definition]
    -- include 'config.trainer_config'

[optimizer]
    == super()
    lr: 3.2e-6

[lr_scheduler]
    == super()
    warmup_steps: 100

#-------------------- config.trainer_config --------------------
-- extends 'project.trainer'

[trainer_args]
    == super()

    # **config**
    # For memory constraints...
    per_device_train_batch_size: 4
    per_device_eval_batch_size: 8
    logging_steps: 4
    eval_steps: 30
    gradient_checkpointing: True
    fuse_optim_with_backward: True
    enable_activation_offloading: True