-- extends 'project.yaml'

[config_metadata]
    == super()
    -- set ns.config_name = "7B 4GPU Pipeline"
    -- set ns.config_description = "7B Model with 4 GPU Pipeline"
    -- set ns.log_name = "i1f1b_4gpu_packed"
    -- set ns.trainer_class = 'trainers/pipeline_trainer.yaml'
    -- set ns.default_max_steps = 250
    -- set ns.max_eval_steps = 10
    -- set ns.nproc_per_node = 4

[trainer_args]
    == super()
    # **config**
    n_microbatches: 8
    is_multistage: True
    stages_per_rank: 2
    per_device_train_batch_size: 8
    per_device_eval_batch_size: 8
    stages_per_rank: 2
    logging_steps: 2
    gradient_checkpointing: True

    # This dataset seems to produce large gradient spikes
    # As long as we have the memory to store the gradients, we
    # can set max_grad_norm to moderate their impact on training.
    max_grad_norm: 75.0

[trainer_definition]
    -- include 'config.trainer_config'

[datacollator]
    == super()
    padding: "max_length" # Required for pipeline

[optimizer]
    == super()
    lr: 6.0e-6

[lr_scheduler]
    == super()
    warmup_steps: 50

#-------------------- config.trainer_config --------------------
-- extends 'project.trainer'
    
[trainer_constructor]
    == super()
    # Config Overrides
    pipe_schedule_factory: !partial:torch.distributed.pipelining:ScheduleInterleaved1F1B
