-- extends "datasets/tokenized_dataset.yaml"

[config_metadata]
    == super()
    -- set ns.config_name = "Fast FineWeb-Edu-Dedup"
    -- set ns.config_description = "FineWeb-Edu-Dedup is a deduplicated subset of the FineWeb-Edu dataset, containing 220 billion tokens of educational web pages."
    -- set ns.source = "https://huggingface.co/datasets/HuggingFaceTB/smollm-corpus"

[train_dataset_split]
train_dataset_split: &train_dataset_split !singleton:forgather.ml.datasets:fast_load_iterable_dataset
    <<: &datasets_split_args
        arg0: "HuggingFaceTB/smollm-corpus"
        arg1: "fineweb-edu-dedup"
    split: "train[10000:]"

[validation_dataset_split]
validation_dataset_split: &validation_dataset_split !singleton:forgather.ml.datasets:fast_load_iterable_dataset
    <<: *datasets_split_args
    split: "train[0:1000]"

[test_dataset_split]
test_dataset_split: &test_dataset_split !singleton:forgather.ml.datasets:fast_load_iterable_dataset
    <<: *datasets_split_args
    split: "train[1000:10000]"

[train_dataset]
train_dataset: &train_dataset !singleton:forgather.ml.datasets:preprocess_dataset
    <<: &dataset_args
        tokenizer: *tokenizer
        fn_kwargs: !var "preprocess_args"
        map_kwargs:
            batch_size: 32
        remove_columns: False
    dataset: *train_dataset_split
    desc: "Tokenizing train"
    
[eval_dataset]
eval_dataset: &eval_dataset !singleton:forgather.ml.datasets:preprocess_dataset
    <<: *dataset_args
    dataset: *validation_dataset_split
    desc: "Tokenizing eval"

[test_dataset]
test_dataset: &test_dataset !singleton:forgather.ml.datasets:preprocess_dataset
    <<: *dataset_args
    dataset: *test_dataset_split
    desc: "Tokenizing test"
