-- extends "configs/default.yaml"

[config_metadata]
    == super()
    -- set ns.config_name = "Llama 30M"
    -- set ns.config_description = "A Llama with 30M parameters"
    -- set ns.model_name = "llama_30m"

[model_definition]
    -- include "config.30M.model"

#------------- config.30M.model --------------
-- extends "config.default.model"

[model_tokenizer]
tokenizer: &tokenizer !call:forgather:from_project
    project_dir: "{{ joinpath(ns.forgather_dir, 'examples', 'tokenizers', 'wikitext') }}"
    config_template: "8k.yaml"

[init_regex_list]
    == super()
    # Erase head init -- embeddings and head are tied
    head: null

[init_f_map]
    == super()
    # When using tied embeddings, we need to change the embedding init
    init_embeddings: !partial:.init_weights:init_embeddings { scale_rsqrt_d_model: True }
    init_output_layer: null

[model_config]
    == super()
    # **30M Overrides**
    hidden_size: {{ hidden_size | toyaml(512) }}
    intermediate_size: {{ intermediate_size | toyaml(1280) }}
    num_attention_heads: {{ num_attention_heads | toyaml(8) }}
    num_hidden_layers: {{ num_hidden_layers | toyaml(10) }}
    num_key_value_heads: {{ num_key_value_heads | toyaml(2) }}
    tie_word_embeddings: True
