-- extends "configs/default.yaml"

[config_metadata]
    == super()
    -- set ns.config_name = "Tiny Llama 4M"
    -- set ns.config_description = "A tiny Llama with 4M parameters"
    -- set ns.model_name = "llama_4m"

[model_definition]
    -- include "config.model"

#------------- config.model --------------
-- extends "config.default.model"

[model_tokenizer]
tokenizer: &tokenizer !call:forgather:from_project
    project_dir: "{{ joinpath(ns.forgather_dir, 'examples', 'tokenizers', 'wikitext') }}"
    config_template: "2k.yaml"
    pp_debug: False

[model_config]
    == super()
    # **4M Overrides**
    hidden_size: {{ hidden_size | default(256) }}
    dim_feedforward: {{ dim_feedforward | default(768) }}
    num_attention_heads: {{ num_attention_heads | default(2) }}
    num_hidden_layers: {{ num_hidden_layers | default(4) }}