-- extends "configs/default.yaml"

## Note that the parent template is configured to be a Llama2 7B, so there's not much here.
[config_metadata]
    == super()
    -- set ns.config_name = "Llama2 7B"
    -- set ns.config_description = "Meta Llama2 7B"
    -- set ns.model_name = model_name | default("llama2_7b")

[model_definition]
    -- include "config.default.model"

#------------- config.default.model --------------
-- extends "models/transformers/dynamic_llama.yaml"

[model_meta_config]
    == super()
    -- set ns.model_name = ns.config_name
    -- set ns.model_description = ns.config_description
    -- set ns.model_short_name = "llama2"

[model_tokenizer]
tokenizer: &tokenizer !singleton:transformers:AutoTokenizer.from_pretrained@tokenizer
    arg0: {{ tokenizer_id_or_path | toyaml('meta-llama/Llama-2-7b') }}
    legacy: False
    max_position_embeddings: {{ max_position_embeddings | toyaml(4096) }}
