-- extends "configs/default.yaml"

[config_metadata]
    == super()
    -- set ns.config_name = "Mistral 119M"
    -- set ns.config_description = "A Mistral with 119M parameters"
    -- set ns.model_name = "mistral_119m"

[model_definition]
    -- include "config.119m.model"

#------------- config.119m.model --------------
-- extends "config.default.model"

[model_tokenizer]
tokenizer: &tokenizer !call:forgather:from_project
    project_dir: "{{ joinpath(ns.forgather_dir, 'examples', 'tokenizers', 'wikitext') }}"
    config_template: "8k.yaml"
    pp_debug: False

[model_config]
    == super()
    # **119M**
    hidden_size: {{ hidden_size | default(1024) }}
    dim_feedforward: {{ dim_feedforward | default(3328) }}
    num_attention_heads: {{ num_attention_heads | default(8) }}
    num_hidden_layers: {{ num_hidden_layers | default(8) }}
    num_kv_heads: {{ num_kv_heads | default(2) }}