-- extends 'samantha.yaml'

[config_metadata]
    == super()
    -- set ns.config_name = "Samantha Llama7B Long"
    -- set ns.config_description = "Train with 4096 token context on single GPU, 24 GBs"
    -- set ns.log_name = "1gpu_4096_packed"
    -- set ns.default_dataset_config = "samantha-packed.yaml"

[trainer_definition]
    -- include 'config.trainer_config'


[datacollator]
    == super()
    packed_sequences: True
    max_length: 4096

[optimizer]
    == super()
    lr: 3.5e-6 # Rescale LR for smaller batch-size

#-------------------- config.trainer_config --------------------
-- extends 'project.trainer'

[trainer_args]
    == super()

    # **config**
    per_device_train_batch_size: 4
    per_device_eval_batch_size: 6
    gradient_checkpointing: True
    fuse_optim_with_backward: True
    enable_activation_offloading: True
