-- extends 'samantha.yaml'

## Packed format packs multiple examples into each 4096 token sequence
## This increases the effective batch size, thus we rescale various 
## parameters to approximate the baseline "1300" sequence length config.
[config_metadata]
    == super()
    -- set ns.config_name = "Samantha Llama7B Packed"
    -- set ns.config_description = "Train with 4096 token context on single GPU, 24 GBs"
    -- set ns.log_name = "1gpu_4096_packed"
    -- set ns.default_dataset_config = "samantha-packed.yaml"

[trainer_definition]
    -- include 'config.trainer_config'

[datasets_preprocessor_args]
# Overrides for forgather.ml.datasets:block_tokenize_fn
.define: &datasets_preprocessor_args !dict
    max_length: 4096

[datacollator]
    == super()
    packed_sequences: True
    max_length: 4096

[optimizer]
    == super()
    lr: 4.0e-6

[lr_scheduler]
    == super()
    warmup_steps: 30

#-------------------- config.trainer_config --------------------
-- extends 'project.trainer'

[trainer_args]
    == super()

    # **config**
    per_device_train_batch_size: 4
    per_device_eval_batch_size: 4
    logging_steps: 2
    eval_steps: 30
    save_steps: 130
    # We need to all the memory we can get for 1 GPU!
    gradient_checkpointing: True
    fuse_optim_with_backward: True
    enable_activation_offloading: True

[trainer_constructor]
    == super()
    # **Config**
    fused_loss_factory: !partial:forgather.ml.loss:LinearCrossEntropyLoss
        impl: "liger"
        chunk_size: 4096
