## Resume training configuration that loads from the latest checkpoint
-- extends "configs/train_iter.yaml"

[config_metadata]
    == super()
    -- set ns.config_name = "Resume Training from Checkpoint -- Iterable"

[trainer_args]
    == super()
    resume_from_checkpoint: True

    # Continue for another 500 steps
    max_steps: 1000