-- extends 'samantha.yaml'

[config_metadata]
    == super()
    -- set ns.config_name = "Samantha Llama 7B i1F1B Pipe x4 Packed"
    -- set ns.config_description = "Samantha Llama 7B i1F1B Pipe x4 with packed sequences"
    -- set ns.log_name = "i1f1b_4gpu_packed"
    -- set ns.trainer_class = 'trainers/pipeline_trainer.yaml'
    -- set ns.default_dataset_config = "samantha-packed.yaml"

[trainer_definition]
    -- include 'config.trainer_config'

[datasets_preprocessor_args]
# Overrides for forgather.ml.datasets:block_tokenize_fn
.define: &datasets_preprocessor_args !dict
    max_length: 4096

[datacollator]
    == super()
    packed_sequences: True
    padding: "max_length" # Required for pipeline
    max_length: 4096

#-------------------- config.trainer_config --------------------
-- extends 'project.trainer'

[trainer_meta_config]
    == super()
    -- set ns.nproc_per_node = 4

[trainer_args]
    == super()
    # **config**
    n_microbatches: 8
    is_multistage: True
    stages_per_rank: 2
    per_device_train_batch_size: 8
    per_device_eval_batch_size: 8
    gradient_checkpointing: True
    fuse_optim_with_backward: True
    
[trainer_constructor]
    == super()
    # Config Overrides
    pipe_schedule_factory: !partial:torch.distributed.pipelining:ScheduleInterleaved1F1B