-- extends "project.yaml"

[config_metadata]
    == super()
    -- set ns.config_name = "Causal LM 23M"
    -- set ns.config_description = "A very vanilla transformer model with 23M parameters"
    -- set ns.model_name = "23m"

[model_definition]
    -- include "config.23M.model"

#------------- config.23M.model --------------
-- extends "models/transformers/dynamic_causal_transformer.yaml"

## This model does not have a default tokenizer, so add one.
[model_tokenizer]
tokenizer: &tokenizer !call:forgather:from_project
    project_dir: "{{ joinpath(ns.forgather_dir, 'examples', 'tokenizers', 'wikitext') }}"
    config_template: "4k.yaml"
    pp_debug: False