-- extends "models/model_type.yaml"

[config_metadata]
    == super()
    -- set ns.config_name = "Tiny Causal LM 4M"
    -- set ns.config_description = "A very tiny vanilla transformer model with 4M parameters"
    -- set ns.model_name = "4m"

[model_definition]
    -- include "config.4M.model"

#------------- config.4M.model --------------
-- extends "models/transformers/dynamic_causal_transformer.yaml"

[model_tokenizer]
tokenizer: &tokenizer !call:forgather:from_project
    project_dir: "{{ joinpath(ns.forgather_dir, 'examples', 'tokenizers', 'wikitext') }}"
    config_template: "2k.yaml"
    pp_debug: False

[model_config]
    == super()
    # **Tiny Causal LM Overrides**
    hidden_size: 256
    intermediate_size: 1024
    num_attention_heads: 4
    num_hidden_layers: 4
    embedding_dropout: 0.0
    layer_dropout: 0.0
    tie_word_embeddings: False