-- extends "project.yaml"

[config_metadata]
    == super()
    -- set ns.config_name = "Causal LM Medium"
    -- set ns.config_description = "A vanilla transformer model with 138M parameters"
    -- set ns.model_name = "medium"

[model_definition]
    -- include "config.medium.model"

#------------- config.medium.model --------------
-- extends "models/transformers/dynamic_causal_transformer.yaml"

[model_tokenizer]
tokenizer: &tokenizer !call:forgather:from_project
    project_dir: "{{ joinpath(ns.forgather_dir, 'examples', 'tokenizers', 'wikitext') }}"
    config_template: "16k.yaml"
    pp_debug: False

[model_config]
    == super()
    # **Medium Causal LM Overrides**
    hidden_size: 768
    intermediate_size: 3072
    num_attention_heads: 8
    num_hidden_layers: 16
    embedding_dropout: 0.0
    layer_dropout: 0.0
