-- extends 'project.yaml'

[config_metadata]
    == super()
    -- set ns.config_name = "Open Orca Llama7B"
    -- set ns.config_description = "Train with 1300 token context on single GPU, 24 GBs"
    -- set ns.log_name = "1gpu_1300"

[trainer_args]
    == super()
    
    # **config**
    per_device_train_batch_size: 8
    per_device_eval_batch_size: 16
    gradient_checkpointing: True
    fuse_optim_with_backward: True

[datacollator]
    == super()
    max_length: 1300
