-- extends 'project.yaml'

[config_metadata]
    == super()
    -- set ns.tokenizer_name = "wikitext_32k"
    -- set ns.config_name = "Wikitext 32K"
    -- set ns.config_description = "32K BPE tokenizer, trained on Wikitext"
    -- set ns.vocab_size = 32000
    -- set ns.model_max_length = 32768
