-- extends "models/model_type.yaml"

[config_metadata]
    == super()
    -- set ns.config_name = "Tiny Llama"
    -- set ns.config_description = "Tiny dynamic Llama model"
    -- set ns.model_name = "llama"

[model_definition]
  -- include "models/tiny/tiny_dyn_llama.yaml"
