-- extends "models/model_type.yaml"

[config_metadata]
    == super()
    -- set ns.config_name = "Tiny"
    -- set ns.config_description = "Default Tiny Model"
    -- set ns.model_name = "tiny"

[model_definition]
  -- include "models/tiny/tiny_causal.yaml"
