-- extends "configs/117M.yaml"

[config_metadata]
    == super()
    -- set ns.config_name = "Pipeline Model"
    -- set ns.config_description = "A medium sized causal model with deepnet layers / init"
    -- set ns.model_name = "pipeline_model"

[model_definition]
    -- include "config.pipeline_model.model"

#------------- config.pipeline_model.model --------------
-- extends "config.117M.model"

[model_config]
    == super()
    # **Pipeline Model**
    hidden_size: 1024
    num_attention_heads: 16
    num_hidden_layers: 16
    embedding_dropout: 0.1
    layer_dropout: 0.1

[layer_factory]
layer_factory: &layer_factory !partial:.deepnet:DeepnetLayer@layer_factory
    feedforward_factory: *feedforward_factory
    attention_factory: *attention_factory
    norm_factory: *layer_norm_factory
    dropout: !var "layer_dropout"
    residual_dropout: !var "residual_dropout"
    alpha: !call:.deepnet:deepnet_alpha@dn_alpha [ !var "num_hidden_layers", 0 ]

[init_weights]
init_weights: &init_weights !partial:.init_weights:init_weights_by_regex@init_weights
    regex_list:
        - [ 'norm', "pass" ]
        - [ 'bias', "zeros" ]
        - [ 'embedding\.weight', "embedding" ]
        - [ 'feedforward|value_linear|output_linear', "deepnet" ]
        - [ 'attention|output_decoder', "linear" ]
    init_f_map:
        pass: !partial:.init_weights:init_pass
        zeros: !partial:torch.nn.init:zeros_ []
        embedding: !partial:.init_weights:init_embeddings
            padding_index: !var "pad_token_id"
        linear: !partial:torch.nn.init:xavier_uniform_ []
        deepnet: !partial:torch.nn.init:xavier_uniform_
            gain: !call:.deepnet:deepnet_beta [ !var "num_hidden_layers", 0 ]