-- extends "project.yaml"

[config_metadata]
    == super()
    -- set ns.config_name = "DDP Trainer 4x"
    -- set ns.config_description = "Test DDP Trainer with 4 GPUs"
    -- set ns.log_name = "4gpu"

[trainer_definition]
    -- include 'config.trainer_config'

[optimizer]
    == super()
    lr: 2.0e-3

#-------------------- config.trainer_config --------------------
-- extends 'project.trainer_config'

[trainer_meta_config]
    == super()
    -- set ns.nproc_per_node = 4