-- extends "project.yaml"

[config_metadata]
    == super()
    -- set ns.config_name = "DDP Trainer 4x"
    -- set ns.config_description = "Test DDP Trainer with 4 GPUs"

[trainer_definition]
    -- include 'config.trainer_config'

#-------------------- config.trainer_config --------------------
-- extends 'project.trainer_config'

[trainer_meta_config]
    == super()
    -- set ns.nproc_per_node = 4