-- extends 'project.yaml'

[config_metadata]
    == super()
    -- set ns.config_name = "Train Canon-B"
    -- set ns.config_description = "Train Canon 4M with only B (attn QKV convolution) layer"
    -- set ns.model_name = "canon_b_4m"
    -- set ns.model_project_config = "canon_b.yaml"
