-- extends 'project.yaml'

[config_metadata]
    == super()
    -- set ns.config_name = "Train Canon Baseline"
    -- set ns.config_description = "Train the Canon baseline 4M model (identical to llama_canon 4M)"
    -- set ns.model_name = "canon_baseline_4m"
    -- set ns.model_project_config = "baseline.yaml"
