-- extends 'project.yaml'

[config_metadata]
    == super()
    -- set ns.config_name = "Train Canon-AB"
    -- set ns.config_description = "Train Canon 4M with A (pre-attn) and B (attn QKV) layers"
    -- set ns.model_name = "canon_ab_4m"
    -- set ns.model_project_config = "canon_ab.yaml"
