-- extends 'project.yaml'

[config_metadata]
    == super()
    -- set ns.config_name = "Train Llama NoPE"
    -- set ns.config_description = "Train a plain Llama 4M model without positional encoding"
    -- set ns.model_name = "llama_nope_4m"
    -- set ns.model_project_dir = joinpath(ns.forgather_dir, 'examples', 'tiny_experiments', 'llama_nope')
    -- set ns.model_project_config = "nope_4M.yaml"
