-- extends 'project.yaml'

[config_metadata]
    == super()
    -- set ns.config_name = "Train Canon-A"
    -- set ns.config_description = "Train Canon 4M with only A (pre-attention convolution)"
    -- set ns.model_name = "canon_a_4m"
    -- set ns.model_project_config = "canon_a.yaml"
