-- extends 'project.yaml'

-- block config_metadata
    == super()
    -- set ns.config_name = "Tiny Deep One"
    -- set ns.config_description = "A tiny Deep One model."
    -- set ns.model_name = "tiny_deepone"
    -- set ns.model_project_dir = joinpath(ns.forgather_dir, 'examples', 'models', 'deepone')
    -- set ns.model_project_config = "4M.yaml"
-- endblock config_metadata