-- extends 'project.yaml'

-- block config_metadata
    == super()
    -- set ns.config_name = "Tiny Forgather Mistral"
    -- set ns.config_description = "A tiny Mistral model with sliding-window attention"
    -- set ns.model_name = "tiny_fg_mistral"
    -- set ns.model_project_dir = joinpath(ns.forgather_dir, 'examples', 'models', 'mistral')
    -- set ns.model_project_config = "4M.yaml"
-- endblock config_metadata
