-- extends 'project.yaml'

[config_metadata]
    == super()
    -- set ns.config_name = "Tiny HF GPT2"
    -- set ns.config_description = "A tiny Huggingface GPT2 model."
    -- set ns.model_name = "tiny_hf_gpt2"


[construct_new_model]
    -- include 'experiment.model_config'

#-------------------- experiment.model_config --------------------
-- extends 'models/tiny/tiny_gpt2.yaml'