-- extends 'project.yaml'

[config_metadata]
    == super()
    -- set ns.config_name = "Tiny HF LLama"
    -- set ns.config_description = "A tiny Huggingface llama model."
    -- set ns.model_name = "tiny_hf_llama"

[construct_new_model]
    -- include 'experiment.model_config'

#-------------------- experiment.model_config --------------------
-- extends 'models/tiny/tiny_llama.yaml'