-- extends 'project.yaml'

[config_metadata]
    == super()
    -- set ns.config_name = "AMP"
    -- set ns.config_description = "Automatic Mixed Precision"
    -- set ns.model_name = "amp"

[trainer_args]
    == super()
    # **AMP**
    default_dtype: "float32"
    mixed_precision: "bf16"

[optimizer]
    == super()
    # **AMP**
    bf16_stochastic_round: False