-- extends 'samantha_packed.yaml'

## Packed format packs multiple examples into each 4096 token sequence
## This increases the effective batch size, thus we rescale various 
## parameters to approximate the baseline "1300" sequence length config.
[config_metadata]
    == super()
    -- set ns.config_name = "Samantha Llama7B Packed"
    -- set ns.config_description = "Train with 4096 token context on single GPU, 24 GBs"
    -- set ns.log_name = log_name | default('1gpu_4096_packed')

[trainer_definition]
    -- include 'config.trainer_config'

[optimizer]
    == super()
    lr: 4.0e-6

[lr_scheduler]
    == super()
    warmup_steps: 30

#-------------------- samantha_packed.trainer_config --------------------
-- extends 'project.trainer'

[trainer_args]
    == super()
    # **config**
    per_device_train_batch_size: 4
    per_device_eval_batch_size: 4
    logging_steps: 2
    eval_steps: 30
    save_steps: 130
    # We need to all the memory we can get for 1 GPU!
    gradient_checkpointing: True
    fuse_optim_with_backward: True
    enable_activation_offloading: True
