-- extends 'samantha.yaml'

[config_metadata]
    == super()
    -- set ns.config_name = "Samantha Llama 7B"
    -- set ns.config_description = "Conservative setting to train a 7B Llaama model on 1 GPU"
    -- set ns.log_name = "default"


[trainer_definition]
    -- include 'config.trainer_config'

[datacollator]
    == super()
    max_length: 1300

#-------------------- config.trainer_config --------------------
-- extends 'project.trainer'

[trainer_args]
    == super()
    # **config**
    gradient_checkpointing: True
    fuse_optim_with_backward: True
    # enable_activation_offloading: True
