-- extends 'samantha_packed.yaml'

## Packed format packs multiple examples into each 4096 token sequence
## This increases the effective batch size, thus we rescale various 
## parameters to approximate the baseline "1300" sequence length config.
[config_metadata]
    == super()
    -- set ns.config_name = "Samantha Llama 7B i1F1B Pipe x2 Packed"
    -- set ns.config_description = "Samantha Llama 7B i1F1B Pipe x2 with packed sequences"
    -- set ns.log_name = log_name | default('i1f1b_2gpu_packed')
    -- set ns.trainer_class = 'trainers/pipeline_trainer.yaml'
    -- set ns.nproc_per_node = 2
    -- set ns.pipe_schedule_factory = "ScheduleInterleaved1F1B"

[trainer_args]
    == super()
    # **config**
    n_microbatches: 4
    is_multistage: True
    stages_per_rank: 2
    logging_steps: 2
    eval_steps: 15
    save_steps: 65
    ## With sequence packing, the effective batch size is ~3.15 times the baseline
    per_device_train_batch_size: 8
    per_device_eval_batch_size: 8
    gradient_checkpointing: True
    fuse_optim_with_backward: True
    #enable_activation_offloading: True

[optimizer]
    == super()
    lr: 4.0e-6

[lr_scheduler]
    == super()
    warmup_steps: 15