-- extends 'samantha_packed.yaml'

[config_metadata]
    == super()
    -- set ns.config_name = "Samantha Llama 7B i1F1B Pipe x4 Packed"
    -- set ns.config_description = "Samantha Llama 7B i1F1B Pipe x4 with packed sequences"
    -- set ns.log_name = log_name | default('i1f1b_4gpu_packed')
    -- set ns.trainer_class = 'trainers/pipeline_trainer.yaml'
    -- set ns.nproc_per_node = 4

[trainer_args]
    == super()
    # **config**
    n_microbatches: 8
    is_multistage: True
    stages_per_rank: 2
    per_device_train_batch_size: 8
    per_device_eval_batch_size: 8
    stages_per_rank: 2
    logging_steps: 2
    eval_steps: 15
    save_steps: 65
    gradient_checkpointing: True
    fuse_optim_with_backward: True
    # enable_activation_offloading: True

[trainer_definition]
    -- include 'config.trainer_config'

[optimizer]
    == super()
    lr: 4.0e-6

[lr_scheduler]
    == super()
    warmup_steps: 15

#-------------------- config.trainer_config --------------------
-- extends 'samantha_packed.trainer'

[trainer_constructor]
    == super()
    # Config Overrides
    pipe_schedule_factory: !partial:torch.distributed.pipelining:ScheduleInterleaved1F1B