-- extends 'samantha.yaml'

[config_metadata]
    == super()
    -- set ns.config_name = "Llama 7B 1F1B Pipe x4 AdamW-4bit"
    -- set ns.config_description = "Train Samantha on 1F1B 4 GPU Pipeline with AdamW-4bit"
    -- set ns.log_name = "1f1b_4gpu_adamw4bit"
    -- set ns.trainer_class = 'trainers/pipeline_trainer.yaml'
    -- set ns.nproc_per_node = 4
    -- set ns.pipe_schedule_factory = "Schedule1F1B"

[trainer_args]
    == super()
    # **config**
    n_microbatches: 4
    per_device_train_batch_size: 8
    per_device_eval_batch_size: 8

[datacollator]
    == super()
    padding: "max_length" # Required for pipeline
    max_length: 1300

[optimizer]
optimizer: &optimizer !partial:torchao.optim:AdamW4bit
    lr: 4.0e-6
    weight_decay: 0.001
